###
#user sign up route
POST http://localhost:3000/user/signup HTTP/1.1
Content-Type : application/json

{
    "username": "mike",
    "email": "mike@gmail.com",
    "password": "12345678"
} 

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNTIyNzdjZDIwMTFkMTk3NjQxYWVlNCIsImlhdCI6MTYzMjc3NDAxMiwiZXhwIjoxNjMzMzc4ODEyfQ.6hMuEnykFypAWfRO6wXRMCQ8v1txEOs-KuiFequ4-K8

###
#user sign in route 
POST http://localhost:3000/user/signin HTTP/1.1
Content-Type : application/json

{
    "email": "abeni@gmail.com",
    "password": "12345678"
} 


###
#Get products
GET http://localhost:3000/data/products?page=1&limit=20 HTTP/1.1
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxNWIzMDAwM2I0YTE4NWVmMGQ2OTA4ZiIsImlhdCI6MTYzMzQ1NTg0MiwiZXhwIjoxNjY0OTkxODQyfQ.lrTfhBmI2OOt1yMlCUu-CKxYIFv_biTgwbnkFOht3dQ

###
#Get userInfo By signing in with token
GET http://localhost:3000/user/signinwithtoken HTTP/1.1
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImlhdCI6MTYzNjYxOTIxOSwiZXhwIjoxNjY4MTU1MjE5fQ.eA3AxIWB8lH71yvxNjTXSDR_BdjnQhoucIyfjOHAuEk

##
##
##
##
##
###
#Get conversation By using senderId and receiverId
GET http://localhost:3000/chat/conv/check?sId=21&rId=19 HTTP/1.1
x-access-token : eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTksImlhdCI6MTYzNjYxOTIxOSwiZXhwIjoxNjY4MTU1MjE5fQ.eA3AxIWB8lH71yvxNjTXSDR_BdjnQhoucIyfjOHAuEk

###
#user sign in route 
PUT http://localhost:3000/chat/conv/updlmsg HTTP/1.1
Content-Type : application/json

{
    "convId": "4",
    "lastMessage": "updated last message",
    "lastMessageTimeSent": "2021-11-07 12:36:17.625196",
    "lastMessageSenderId": "20"
} 